/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1AddressReverseRequest = {
  /**
   * Latitude in decimal degrees.
   */
  lat: number;
  /**
   * Longitude in decimal degrees.
   */
  lon: number;
  /**
   * Search radius in metres.
   */
  radius?: number | undefined;
  /**
   * Maximum number of nearby addresses to return.
   */
  limit?: number | undefined;
};

/**
 * Physical location and geocoding metadata.
 */
export type GetV1AddressReverseGeocode = {
  /**
   * Latitude in decimal degrees.
   */
  latitude: number;
  /**
   * Longitude in decimal degrees.
   */
  longitude: number;
  /**
   * Geocoding method, e.g. PROPERTY CENTROID.
   */
  type?: string | undefined;
  /**
   * G-NAF geocode reliability (0-6, lower is better).
   */
  reliability?: number | undefined;
};

/**
 * OpenSearch geo_point format.
 */
export type GetV1AddressReverseLocation = {
  /**
   * Latitude.
   */
  lat: number;
  /**
   * Longitude.
   */
  lon: number;
};

/**
 * Local Government Area.
 */
export type GetV1AddressReverseLga = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * State electoral district.
 */
export type GetV1AddressReverseStateElectorate = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Federal electoral district.
 */
export type GetV1AddressReverseCommonwealthElectorate = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * ABS smallest geographic unit.
 */
export type GetV1AddressReverseMeshBlock = {
  /**
   * ABS mesh block code.
   */
  code: string;
  /**
   * Land use category, e.g. Residential, Commercial.
   */
  category?: string | undefined;
};

/**
 * Statistical Area Level 2.
 */
export type GetV1AddressReverseSa2 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Statistical Area Level 3.
 */
export type GetV1AddressReverseSa3 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Statistical Area Level 4.
 */
export type GetV1AddressReverseSa4 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Greater Capital City Statistical Area.
 */
export type GetV1AddressReverseGccsa = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Electoral, administrative, and statistical boundaries.
 */
export type GetV1AddressReverseBoundaries = {
  /**
   * Local Government Area.
   */
  lga?: GetV1AddressReverseLga | undefined;
  /**
   * State electoral district.
   */
  stateElectorate?: GetV1AddressReverseStateElectorate | undefined;
  /**
   * Federal electoral district.
   */
  commonwealthElectorate?:
    | GetV1AddressReverseCommonwealthElectorate
    | undefined;
  /**
   * ABS smallest geographic unit.
   */
  meshBlock?: GetV1AddressReverseMeshBlock | undefined;
  /**
   * Statistical Area Level 2.
   */
  sa2?: GetV1AddressReverseSa2 | undefined;
  /**
   * Statistical Area Level 3.
   */
  sa3?: GetV1AddressReverseSa3 | undefined;
  /**
   * Statistical Area Level 4.
   */
  sa4?: GetV1AddressReverseSa4 | undefined;
  /**
   * Greater Capital City Statistical Area.
   */
  gccsa?: GetV1AddressReverseGccsa | undefined;
};

export type Results = {
  /**
   * G-NAF persistent identifier.
   */
  id: string;
  /**
   * Street address (number + street name).
   */
  addressLabel?: string | undefined;
  /**
   * Suburb or locality name.
   */
  localityName?: string | undefined;
  /**
   * Australian state code (NSW, VIC, QLD, SA, WA, TAS, NT, ACT).
   */
  state?: string | undefined;
  /**
   * 4-digit Australian postcode.
   */
  postcode?: string | undefined;
  /**
   * G-NAF confidence level (0-2).
   */
  confidence?: number | undefined;
  /**
   * Physical location and geocoding metadata.
   */
  geocode?: GetV1AddressReverseGeocode | undefined;
  /**
   * OpenSearch geo_point format.
   */
  location?: GetV1AddressReverseLocation | undefined;
  /**
   * Electoral, administrative, and statistical boundaries.
   */
  boundaries?: GetV1AddressReverseBoundaries | undefined;
  /**
   * Distance from query point in meters.
   */
  distanceM?: number | undefined;
};

/**
 * Nearby addresses
 */
export type GetV1AddressReverseResponseBody = {
  results: Array<Results>;
  /**
   * Total addresses within radius.
   */
  total: number;
};

export type GetV1AddressReverseResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1AddressReverseResponseBody;
};

/** @internal */
export type GetV1AddressReverseRequest$Outbound = {
  lat: number;
  lon: number;
  radius: number;
  limit: number;
};

/** @internal */
export const GetV1AddressReverseRequest$outboundSchema: z.ZodMiniType<
  GetV1AddressReverseRequest$Outbound,
  GetV1AddressReverseRequest
> = z.object({
  lat: z.number(),
  lon: z.number(),
  radius: z._default(z.number(), 100),
  limit: z._default(z.int(), 5),
});

export function getV1AddressReverseRequestToJSON(
  getV1AddressReverseRequest: GetV1AddressReverseRequest,
): string {
  return JSON.stringify(
    GetV1AddressReverseRequest$outboundSchema.parse(getV1AddressReverseRequest),
  );
}

/** @internal */
export const GetV1AddressReverseGeocode$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseGeocode,
  unknown
> = z.object({
  latitude: types.number(),
  longitude: types.number(),
  type: types.optional(types.string()),
  reliability: types.optional(types.number()),
});

export function getV1AddressReverseGeocodeFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseGeocode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseGeocode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseGeocode' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseLocation$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseLocation,
  unknown
> = z.object({
  lat: types.number(),
  lon: types.number(),
});

export function getV1AddressReverseLocationFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseLocation' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseLga$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseLga,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressReverseLgaFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseLga, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseLga$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseLga' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseStateElectorate$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseStateElectorate,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressReverseStateElectorateFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseStateElectorate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressReverseStateElectorate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseStateElectorate' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseCommonwealthElectorate$inboundSchema:
  z.ZodMiniType<GetV1AddressReverseCommonwealthElectorate, unknown> = z.object({
    name: types.string(),
    code: types.optional(types.string()),
  });

export function getV1AddressReverseCommonwealthElectorateFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressReverseCommonwealthElectorate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressReverseCommonwealthElectorate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressReverseCommonwealthElectorate' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseMeshBlock$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseMeshBlock,
  unknown
> = z.object({
  code: types.string(),
  category: types.optional(types.string()),
});

export function getV1AddressReverseMeshBlockFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseMeshBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseMeshBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseMeshBlock' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseSa2$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseSa2,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressReverseSa2FromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseSa2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseSa2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseSa2' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseSa3$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseSa3,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressReverseSa3FromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseSa3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseSa3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseSa3' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseSa4$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseSa4,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressReverseSa4FromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseSa4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseSa4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseSa4' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseGccsa$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseGccsa,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressReverseGccsaFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseGccsa, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseGccsa$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseGccsa' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseBoundaries$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseBoundaries,
  unknown
> = z.object({
  lga: types.optional(z.lazy(() => GetV1AddressReverseLga$inboundSchema)),
  stateElectorate: types.optional(
    z.lazy(() => GetV1AddressReverseStateElectorate$inboundSchema),
  ),
  commonwealthElectorate: types.optional(
    z.lazy(() => GetV1AddressReverseCommonwealthElectorate$inboundSchema),
  ),
  meshBlock: types.optional(
    z.lazy(() => GetV1AddressReverseMeshBlock$inboundSchema),
  ),
  sa2: types.optional(z.lazy(() => GetV1AddressReverseSa2$inboundSchema)),
  sa3: types.optional(z.lazy(() => GetV1AddressReverseSa3$inboundSchema)),
  sa4: types.optional(z.lazy(() => GetV1AddressReverseSa4$inboundSchema)),
  gccsa: types.optional(z.lazy(() => GetV1AddressReverseGccsa$inboundSchema)),
});

export function getV1AddressReverseBoundariesFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseBoundaries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseBoundaries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseBoundaries' from JSON`,
  );
}

/** @internal */
export const Results$inboundSchema: z.ZodMiniType<Results, unknown> = z.pipe(
  z.object({
    id: types.string(),
    addressLabel: types.optional(types.string()),
    localityName: types.optional(types.string()),
    state: types.optional(types.string()),
    postcode: types.optional(types.string()),
    confidence: types.optional(types.number()),
    geocode: types.optional(z.lazy(() =>
      GetV1AddressReverseGeocode$inboundSchema
    )),
    location: types.optional(z.lazy(() =>
      GetV1AddressReverseLocation$inboundSchema
    )),
    boundaries: types.optional(z.lazy(() =>
      GetV1AddressReverseBoundaries$inboundSchema
    )),
    distance_m: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "distance_m": "distanceM",
    });
  }),
);

export function resultsFromJSON(
  jsonString: string,
): SafeParseResult<Results, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Results$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Results' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseResponseBody,
  unknown
> = z.object({
  results: z.array(z.lazy(() => Results$inboundSchema)),
  total: types.number(),
});

export function getV1AddressReverseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseResponse$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1AddressReverseResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1AddressReverseResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseResponse' from JSON`,
  );
}
