/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1AddressLookupPostcodeRequest = {
  /**
   * Australian 4-digit postcode.
   */
  postcode: string;
  /**
   * Maximum number of localities to return.
   */
  limit?: number | undefined;
};

export type Localities = {
  /**
   * Locality/suburb name.
   */
  name: string;
  /**
   * State code.
   */
  state?: string | undefined;
  /**
   * Number of addresses in this locality.
   */
  addressCount: number;
};

/**
 * Postcode locality summary
 */
export type GetV1AddressLookupPostcodeResponseBody = {
  /**
   * The queried postcode.
   */
  postcode: string;
  localities: Array<Localities>;
};

/** @internal */
export type GetV1AddressLookupPostcodeRequest$Outbound = {
  postcode: string;
  limit: number;
};

/** @internal */
export const GetV1AddressLookupPostcodeRequest$outboundSchema: z.ZodMiniType<
  GetV1AddressLookupPostcodeRequest$Outbound,
  GetV1AddressLookupPostcodeRequest
> = z.object({
  postcode: z.string(),
  limit: z._default(z.int(), 10),
});

export function getV1AddressLookupPostcodeRequestToJSON(
  getV1AddressLookupPostcodeRequest: GetV1AddressLookupPostcodeRequest,
): string {
  return JSON.stringify(
    GetV1AddressLookupPostcodeRequest$outboundSchema.parse(
      getV1AddressLookupPostcodeRequest,
    ),
  );
}

/** @internal */
export const Localities$inboundSchema: z.ZodMiniType<Localities, unknown> = z
  .pipe(
    z.object({
      name: types.string(),
      state: types.optional(types.string()),
      address_count: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "address_count": "addressCount",
      });
    }),
  );

export function localitiesFromJSON(
  jsonString: string,
): SafeParseResult<Localities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Localities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Localities' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupPostcodeResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponseBody, unknown> = z.object({
    postcode: types.string(),
    localities: z.array(z.lazy(() => Localities$inboundSchema)),
  });

export function getV1AddressLookupPostcodeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressLookupPostcodeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupPostcodeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressLookupPostcodeResponseBody' from JSON`,
  );
}
