/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1AddressLookupSuburbRequest = {
  /**
   * Suburb/locality name.
   */
  suburb: string;
  /**
   * Australian state code.
   */
  state?: string | undefined;
  /**
   * Maximum number of postcodes to return.
   */
  limit?: number | undefined;
};

/**
 * North-west corner of bounding box.
 */
export type TopLeft = {
  /**
   * Latitude.
   */
  lat: number;
  /**
   * Longitude.
   */
  lon: number;
};

/**
 * South-east corner of bounding box.
 */
export type BottomRight = {
  /**
   * Latitude.
   */
  lat: number;
  /**
   * Longitude.
   */
  lon: number;
};

/**
 * Geographic bounding box of the suburb.
 */
export type Bounds = {
  /**
   * North-west corner of bounding box.
   */
  topLeft: TopLeft;
  /**
   * South-east corner of bounding box.
   */
  bottomRight: BottomRight;
};

/**
 * Suburb postcode summary
 */
export type GetV1AddressLookupSuburbResponseBody = {
  /**
   * Normalised suburb name (uppercase).
   */
  suburb: string;
  /**
   * State filter applied, if any.
   */
  state?: string | undefined;
  /**
   * Postcodes covering this suburb.
   */
  postcodes: Array<string>;
  /**
   * Geographic bounding box of the suburb.
   */
  bounds?: Bounds | undefined;
  /**
   * Total addresses in this suburb.
   */
  addressCount: number;
};

/** @internal */
export type GetV1AddressLookupSuburbRequest$Outbound = {
  suburb: string;
  state?: string | undefined;
  limit: number;
};

/** @internal */
export const GetV1AddressLookupSuburbRequest$outboundSchema: z.ZodMiniType<
  GetV1AddressLookupSuburbRequest$Outbound,
  GetV1AddressLookupSuburbRequest
> = z.object({
  suburb: z.string(),
  state: z.optional(z.string()),
  limit: z._default(z.int(), 10),
});

export function getV1AddressLookupSuburbRequestToJSON(
  getV1AddressLookupSuburbRequest: GetV1AddressLookupSuburbRequest,
): string {
  return JSON.stringify(
    GetV1AddressLookupSuburbRequest$outboundSchema.parse(
      getV1AddressLookupSuburbRequest,
    ),
  );
}

/** @internal */
export const TopLeft$inboundSchema: z.ZodMiniType<TopLeft, unknown> = z.object({
  lat: types.number(),
  lon: types.number(),
});

export function topLeftFromJSON(
  jsonString: string,
): SafeParseResult<TopLeft, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopLeft$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopLeft' from JSON`,
  );
}

/** @internal */
export const BottomRight$inboundSchema: z.ZodMiniType<BottomRight, unknown> = z
  .object({
    lat: types.number(),
    lon: types.number(),
  });

export function bottomRightFromJSON(
  jsonString: string,
): SafeParseResult<BottomRight, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BottomRight$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BottomRight' from JSON`,
  );
}

/** @internal */
export const Bounds$inboundSchema: z.ZodMiniType<Bounds, unknown> = z.pipe(
  z.object({
    top_left: z.lazy(() => TopLeft$inboundSchema),
    bottom_right: z.lazy(() => BottomRight$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "top_left": "topLeft",
      "bottom_right": "bottomRight",
    });
  }),
);

export function boundsFromJSON(
  jsonString: string,
): SafeParseResult<Bounds, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bounds$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bounds' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupSuburbResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressLookupSuburbResponseBody,
  unknown
> = z.pipe(
  z.object({
    suburb: types.string(),
    state: types.optional(types.string()),
    postcodes: z.array(types.string()),
    bounds: types.optional(z.lazy(() => Bounds$inboundSchema)),
    address_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "address_count": "addressCount",
    });
  }),
);

export function getV1AddressLookupSuburbResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressLookupSuburbResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupSuburbResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressLookupSuburbResponseBody' from JSON`,
  );
}
