/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1AddressAutocompleteRequest = {
  /**
   * Partial address query.
   */
  q: string;
  /**
   * Australian state code.
   */
  state?: string | undefined;
  /**
   * Maximum number of suggestions to return.
   */
  limit?: number | undefined;
};

export type Suggestions = {
  /**
   * G-NAF persistent identifier.
   */
  id: string;
  /**
   * Street address (number + street name).
   */
  addressLabel?: string | undefined;
  /**
   * Suburb or locality name.
   */
  localityName?: string | undefined;
  /**
   * Australian state code.
   */
  state?: string | undefined;
  /**
   * 4-digit Australian postcode.
   */
  postcode?: string | undefined;
  /**
   * G-NAF confidence level (0-2).
   */
  confidence?: number | undefined;
  /**
   * Search relevance score.
   */
  score?: number | undefined;
};

/**
 * Address suggestions
 */
export type GetV1AddressAutocompleteResponseBody = {
  suggestions: Array<Suggestions>;
  /**
   * Total matching addresses.
   */
  total: number;
};

/** @internal */
export type GetV1AddressAutocompleteRequest$Outbound = {
  q: string;
  state?: string | undefined;
  limit: number;
};

/** @internal */
export const GetV1AddressAutocompleteRequest$outboundSchema: z.ZodMiniType<
  GetV1AddressAutocompleteRequest$Outbound,
  GetV1AddressAutocompleteRequest
> = z.object({
  q: z.string(),
  state: z.optional(z.string()),
  limit: z._default(z.int(), 5),
});

export function getV1AddressAutocompleteRequestToJSON(
  getV1AddressAutocompleteRequest: GetV1AddressAutocompleteRequest,
): string {
  return JSON.stringify(
    GetV1AddressAutocompleteRequest$outboundSchema.parse(
      getV1AddressAutocompleteRequest,
    ),
  );
}

/** @internal */
export const Suggestions$inboundSchema: z.ZodMiniType<Suggestions, unknown> = z
  .object({
    id: types.string(),
    addressLabel: types.optional(types.string()),
    localityName: types.optional(types.string()),
    state: types.optional(types.string()),
    postcode: types.optional(types.string()),
    confidence: types.optional(types.number()),
    score: types.optional(types.number()),
  });

export function suggestionsFromJSON(
  jsonString: string,
): SafeParseResult<Suggestions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Suggestions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Suggestions' from JSON`,
  );
}

/** @internal */
export const GetV1AddressAutocompleteResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressAutocompleteResponseBody,
  unknown
> = z.object({
  suggestions: z.array(z.lazy(() => Suggestions$inboundSchema)),
  total: types.number(),
});

export function getV1AddressAutocompleteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressAutocompleteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressAutocompleteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressAutocompleteResponseBody' from JSON`,
  );
}
