/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1AddressEnrichRequest = {
  /**
   * G-NAF address document ID.
   */
  id: string;
};

/**
 * Physical location and geocoding metadata.
 */
export type Geocode = {
  /**
   * Latitude in decimal degrees.
   */
  latitude: number;
  /**
   * Longitude in decimal degrees.
   */
  longitude: number;
  /**
   * Geocoding method, e.g. PROPERTY CENTROID.
   */
  type?: string | undefined;
  /**
   * G-NAF geocode reliability (0-6, lower is better).
   */
  reliability?: number | undefined;
};

/**
 * OpenSearch geo_point format.
 */
export type Location = {
  /**
   * Latitude.
   */
  lat: number;
  /**
   * Longitude.
   */
  lon: number;
};

/**
 * Local Government Area.
 */
export type Lga = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * State electoral district.
 */
export type StateElectorate = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Federal electoral district.
 */
export type CommonwealthElectorate = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * ABS smallest geographic unit.
 */
export type MeshBlock = {
  /**
   * ABS mesh block code.
   */
  code: string;
  /**
   * Land use category, e.g. Residential, Commercial.
   */
  category?: string | undefined;
};

/**
 * Statistical Area Level 2.
 */
export type Sa2 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Statistical Area Level 3.
 */
export type Sa3 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Statistical Area Level 4.
 */
export type Sa4 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Greater Capital City Statistical Area.
 */
export type Gccsa = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Electoral, administrative, and statistical boundaries.
 */
export type Boundaries = {
  /**
   * Local Government Area.
   */
  lga?: Lga | undefined;
  /**
   * State electoral district.
   */
  stateElectorate?: StateElectorate | undefined;
  /**
   * Federal electoral district.
   */
  commonwealthElectorate?: CommonwealthElectorate | undefined;
  /**
   * ABS smallest geographic unit.
   */
  meshBlock?: MeshBlock | undefined;
  /**
   * Statistical Area Level 2.
   */
  sa2?: Sa2 | undefined;
  /**
   * Statistical Area Level 3.
   */
  sa3?: Sa3 | undefined;
  /**
   * Statistical Area Level 4.
   */
  sa4?: Sa4 | undefined;
  /**
   * Greater Capital City Statistical Area.
   */
  gccsa?: Gccsa | undefined;
};

/**
 * Enriched address document
 */
export type GetV1AddressEnrichResponseBody = {
  /**
   * G-NAF persistent identifier.
   */
  id: string;
  /**
   * Street address (number + street name).
   */
  addressLabel?: string | undefined;
  /**
   * Suburb or locality name.
   */
  localityName?: string | undefined;
  /**
   * Australian state code (NSW, VIC, QLD, SA, WA, TAS, NT, ACT).
   */
  state?: string | undefined;
  /**
   * 4-digit Australian postcode.
   */
  postcode?: string | undefined;
  /**
   * G-NAF confidence level (0-2).
   */
  confidence?: number | undefined;
  /**
   * Physical location and geocoding metadata.
   */
  geocode?: Geocode | undefined;
  /**
   * OpenSearch geo_point format.
   */
  location?: Location | undefined;
  /**
   * Electoral, administrative, and statistical boundaries.
   */
  boundaries?: Boundaries | undefined;
};

export type GetV1AddressEnrichResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1AddressEnrichResponseBody;
};

/** @internal */
export type GetV1AddressEnrichRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1AddressEnrichRequest$outboundSchema: z.ZodMiniType<
  GetV1AddressEnrichRequest$Outbound,
  GetV1AddressEnrichRequest
> = z.object({
  id: z.string(),
});

export function getV1AddressEnrichRequestToJSON(
  getV1AddressEnrichRequest: GetV1AddressEnrichRequest,
): string {
  return JSON.stringify(
    GetV1AddressEnrichRequest$outboundSchema.parse(getV1AddressEnrichRequest),
  );
}

/** @internal */
export const Geocode$inboundSchema: z.ZodMiniType<Geocode, unknown> = z.object({
  latitude: types.number(),
  longitude: types.number(),
  type: types.optional(types.string()),
  reliability: types.optional(types.number()),
});

export function geocodeFromJSON(
  jsonString: string,
): SafeParseResult<Geocode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Geocode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Geocode' from JSON`,
  );
}

/** @internal */
export const Location$inboundSchema: z.ZodMiniType<Location, unknown> = z
  .object({
    lat: types.number(),
    lon: types.number(),
  });

export function locationFromJSON(
  jsonString: string,
): SafeParseResult<Location, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Location$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Location' from JSON`,
  );
}

/** @internal */
export const Lga$inboundSchema: z.ZodMiniType<Lga, unknown> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function lgaFromJSON(
  jsonString: string,
): SafeParseResult<Lga, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lga$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lga' from JSON`,
  );
}

/** @internal */
export const StateElectorate$inboundSchema: z.ZodMiniType<
  StateElectorate,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function stateElectorateFromJSON(
  jsonString: string,
): SafeParseResult<StateElectorate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StateElectorate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StateElectorate' from JSON`,
  );
}

/** @internal */
export const CommonwealthElectorate$inboundSchema: z.ZodMiniType<
  CommonwealthElectorate,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function commonwealthElectorateFromJSON(
  jsonString: string,
): SafeParseResult<CommonwealthElectorate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommonwealthElectorate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommonwealthElectorate' from JSON`,
  );
}

/** @internal */
export const MeshBlock$inboundSchema: z.ZodMiniType<MeshBlock, unknown> = z
  .object({
    code: types.string(),
    category: types.optional(types.string()),
  });

export function meshBlockFromJSON(
  jsonString: string,
): SafeParseResult<MeshBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeshBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeshBlock' from JSON`,
  );
}

/** @internal */
export const Sa2$inboundSchema: z.ZodMiniType<Sa2, unknown> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function sa2FromJSON(
  jsonString: string,
): SafeParseResult<Sa2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sa2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sa2' from JSON`,
  );
}

/** @internal */
export const Sa3$inboundSchema: z.ZodMiniType<Sa3, unknown> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function sa3FromJSON(
  jsonString: string,
): SafeParseResult<Sa3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sa3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sa3' from JSON`,
  );
}

/** @internal */
export const Sa4$inboundSchema: z.ZodMiniType<Sa4, unknown> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function sa4FromJSON(
  jsonString: string,
): SafeParseResult<Sa4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sa4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sa4' from JSON`,
  );
}

/** @internal */
export const Gccsa$inboundSchema: z.ZodMiniType<Gccsa, unknown> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function gccsaFromJSON(
  jsonString: string,
): SafeParseResult<Gccsa, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Gccsa$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Gccsa' from JSON`,
  );
}

/** @internal */
export const Boundaries$inboundSchema: z.ZodMiniType<Boundaries, unknown> = z
  .object({
    lga: types.optional(z.lazy(() => Lga$inboundSchema)),
    stateElectorate: types.optional(
      z.lazy(() => StateElectorate$inboundSchema),
    ),
    commonwealthElectorate: types.optional(
      z.lazy(() => CommonwealthElectorate$inboundSchema),
    ),
    meshBlock: types.optional(z.lazy(() => MeshBlock$inboundSchema)),
    sa2: types.optional(z.lazy(() => Sa2$inboundSchema)),
    sa3: types.optional(z.lazy(() => Sa3$inboundSchema)),
    sa4: types.optional(z.lazy(() => Sa4$inboundSchema)),
    gccsa: types.optional(z.lazy(() => Gccsa$inboundSchema)),
  });

export function boundariesFromJSON(
  jsonString: string,
): SafeParseResult<Boundaries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Boundaries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Boundaries' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponseBody,
  unknown
> = z.object({
  id: types.string(),
  addressLabel: types.optional(types.string()),
  localityName: types.optional(types.string()),
  state: types.optional(types.string()),
  postcode: types.optional(types.string()),
  confidence: types.optional(types.number()),
  geocode: types.optional(z.lazy(() => Geocode$inboundSchema)),
  location: types.optional(z.lazy(() => Location$inboundSchema)),
  boundaries: types.optional(z.lazy(() => Boundaries$inboundSchema)),
});

export function getV1AddressEnrichResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressEnrichResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponse$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1AddressEnrichResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1AddressEnrichResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressEnrichResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichResponse' from JSON`,
  );
}
