/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1AddressValidateRequest = {
  /**
   * Full address string to validate.
   */
  q: string;
};

/**
 * Physical location and geocoding metadata.
 */
export type GetV1AddressValidateGeocode = {
  /**
   * Latitude in decimal degrees.
   */
  latitude: number;
  /**
   * Longitude in decimal degrees.
   */
  longitude: number;
  /**
   * Geocoding method, e.g. PROPERTY CENTROID.
   */
  type?: string | undefined;
  /**
   * G-NAF geocode reliability (0-6, lower is better).
   */
  reliability?: number | undefined;
};

/**
 * OpenSearch geo_point format.
 */
export type GetV1AddressValidateLocation = {
  /**
   * Latitude.
   */
  lat: number;
  /**
   * Longitude.
   */
  lon: number;
};

/**
 * Local Government Area.
 */
export type GetV1AddressValidateLga = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * State electoral district.
 */
export type GetV1AddressValidateStateElectorate = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Federal electoral district.
 */
export type GetV1AddressValidateCommonwealthElectorate = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * ABS smallest geographic unit.
 */
export type GetV1AddressValidateMeshBlock = {
  /**
   * ABS mesh block code.
   */
  code: string;
  /**
   * Land use category, e.g. Residential, Commercial.
   */
  category?: string | undefined;
};

/**
 * Statistical Area Level 2.
 */
export type GetV1AddressValidateSa2 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Statistical Area Level 3.
 */
export type GetV1AddressValidateSa3 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Statistical Area Level 4.
 */
export type GetV1AddressValidateSa4 = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Greater Capital City Statistical Area.
 */
export type GetV1AddressValidateGccsa = {
  /**
   * Area name.
   */
  name: string;
  /**
   * ABS area code.
   */
  code?: string | undefined;
};

/**
 * Electoral, administrative, and statistical boundaries.
 */
export type GetV1AddressValidateBoundaries = {
  /**
   * Local Government Area.
   */
  lga?: GetV1AddressValidateLga | undefined;
  /**
   * State electoral district.
   */
  stateElectorate?: GetV1AddressValidateStateElectorate | undefined;
  /**
   * Federal electoral district.
   */
  commonwealthElectorate?:
    | GetV1AddressValidateCommonwealthElectorate
    | undefined;
  /**
   * ABS smallest geographic unit.
   */
  meshBlock?: GetV1AddressValidateMeshBlock | undefined;
  /**
   * Statistical Area Level 2.
   */
  sa2?: GetV1AddressValidateSa2 | undefined;
  /**
   * Statistical Area Level 3.
   */
  sa3?: GetV1AddressValidateSa3 | undefined;
  /**
   * Statistical Area Level 4.
   */
  sa4?: GetV1AddressValidateSa4 | undefined;
  /**
   * Greater Capital City Statistical Area.
   */
  gccsa?: GetV1AddressValidateGccsa | undefined;
};

/**
 * Best matching address, or null if no match.
 */
export type Match = {
  /**
   * G-NAF persistent identifier.
   */
  id: string;
  /**
   * Street address (number + street name).
   */
  addressLabel?: string | undefined;
  /**
   * Suburb or locality name.
   */
  localityName?: string | undefined;
  /**
   * Australian state code (NSW, VIC, QLD, SA, WA, TAS, NT, ACT).
   */
  state?: string | undefined;
  /**
   * 4-digit Australian postcode.
   */
  postcode?: string | undefined;
  /**
   * G-NAF confidence level (0-2).
   */
  confidence?: number | undefined;
  /**
   * Physical location and geocoding metadata.
   */
  geocode?: GetV1AddressValidateGeocode | undefined;
  /**
   * OpenSearch geo_point format.
   */
  location?: GetV1AddressValidateLocation | undefined;
  /**
   * Electoral, administrative, and statistical boundaries.
   */
  boundaries?: GetV1AddressValidateBoundaries | undefined;
};

/**
 * Match confidence: high (score > 20), medium (10-20), low (< 10), or none (no match).
 */
export const Confidence = {
  High: "high",
  Medium: "medium",
  Low: "low",
  None: "none",
} as const;
/**
 * Match confidence: high (score > 20), medium (10-20), low (< 10), or none (no match).
 */
export type Confidence = OpenEnum<typeof Confidence>;

/**
 * Best address match
 */
export type GetV1AddressValidateResponseBody = {
  /**
   * Best matching address, or null if no match.
   */
  match: Match | null;
  /**
   * Match confidence: high (score > 20), medium (10-20), low (< 10), or none (no match).
   */
  confidence: Confidence;
};

export type GetV1AddressValidateResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1AddressValidateResponseBody;
};

/** @internal */
export type GetV1AddressValidateRequest$Outbound = {
  q: string;
};

/** @internal */
export const GetV1AddressValidateRequest$outboundSchema: z.ZodMiniType<
  GetV1AddressValidateRequest$Outbound,
  GetV1AddressValidateRequest
> = z.object({
  q: z.string(),
});

export function getV1AddressValidateRequestToJSON(
  getV1AddressValidateRequest: GetV1AddressValidateRequest,
): string {
  return JSON.stringify(
    GetV1AddressValidateRequest$outboundSchema.parse(
      getV1AddressValidateRequest,
    ),
  );
}

/** @internal */
export const GetV1AddressValidateGeocode$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateGeocode,
  unknown
> = z.object({
  latitude: types.number(),
  longitude: types.number(),
  type: types.optional(types.string()),
  reliability: types.optional(types.number()),
});

export function getV1AddressValidateGeocodeFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateGeocode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateGeocode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateGeocode' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateLocation$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateLocation,
  unknown
> = z.object({
  lat: types.number(),
  lon: types.number(),
});

export function getV1AddressValidateLocationFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateLocation' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateLga$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateLga,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressValidateLgaFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateLga, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateLga$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateLga' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateStateElectorate$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateStateElectorate,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressValidateStateElectorateFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateStateElectorate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressValidateStateElectorate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateStateElectorate' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateCommonwealthElectorate$inboundSchema:
  z.ZodMiniType<GetV1AddressValidateCommonwealthElectorate, unknown> = z.object(
    {
      name: types.string(),
      code: types.optional(types.string()),
    },
  );

export function getV1AddressValidateCommonwealthElectorateFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressValidateCommonwealthElectorate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressValidateCommonwealthElectorate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressValidateCommonwealthElectorate' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateMeshBlock$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateMeshBlock,
  unknown
> = z.object({
  code: types.string(),
  category: types.optional(types.string()),
});

export function getV1AddressValidateMeshBlockFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateMeshBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateMeshBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateMeshBlock' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateSa2$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateSa2,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressValidateSa2FromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateSa2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateSa2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateSa2' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateSa3$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateSa3,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressValidateSa3FromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateSa3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateSa3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateSa3' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateSa4$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateSa4,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressValidateSa4FromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateSa4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateSa4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateSa4' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateGccsa$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateGccsa,
  unknown
> = z.object({
  name: types.string(),
  code: types.optional(types.string()),
});

export function getV1AddressValidateGccsaFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateGccsa, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateGccsa$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateGccsa' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateBoundaries$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateBoundaries,
  unknown
> = z.object({
  lga: types.optional(z.lazy(() => GetV1AddressValidateLga$inboundSchema)),
  stateElectorate: types.optional(
    z.lazy(() => GetV1AddressValidateStateElectorate$inboundSchema),
  ),
  commonwealthElectorate: types.optional(
    z.lazy(() => GetV1AddressValidateCommonwealthElectorate$inboundSchema),
  ),
  meshBlock: types.optional(
    z.lazy(() => GetV1AddressValidateMeshBlock$inboundSchema),
  ),
  sa2: types.optional(z.lazy(() => GetV1AddressValidateSa2$inboundSchema)),
  sa3: types.optional(z.lazy(() => GetV1AddressValidateSa3$inboundSchema)),
  sa4: types.optional(z.lazy(() => GetV1AddressValidateSa4$inboundSchema)),
  gccsa: types.optional(z.lazy(() => GetV1AddressValidateGccsa$inboundSchema)),
});

export function getV1AddressValidateBoundariesFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateBoundaries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateBoundaries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateBoundaries' from JSON`,
  );
}

/** @internal */
export const Match$inboundSchema: z.ZodMiniType<Match, unknown> = z.object({
  id: types.string(),
  addressLabel: types.optional(types.string()),
  localityName: types.optional(types.string()),
  state: types.optional(types.string()),
  postcode: types.optional(types.string()),
  confidence: types.optional(types.number()),
  geocode: types.optional(
    z.lazy(() => GetV1AddressValidateGeocode$inboundSchema),
  ),
  location: types.optional(
    z.lazy(() => GetV1AddressValidateLocation$inboundSchema),
  ),
  boundaries: types.optional(
    z.lazy(() => GetV1AddressValidateBoundaries$inboundSchema),
  ),
});

export function matchFromJSON(
  jsonString: string,
): SafeParseResult<Match, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Match$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Match' from JSON`,
  );
}

/** @internal */
export const Confidence$inboundSchema: z.ZodMiniType<Confidence, unknown> =
  openEnums.inboundSchema(Confidence);

/** @internal */
export const GetV1AddressValidateResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateResponseBody,
  unknown
> = z.object({
  match: types.nullable(z.lazy(() => Match$inboundSchema)),
  confidence: Confidence$inboundSchema,
});

export function getV1AddressValidateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateResponse$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1AddressValidateResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1AddressValidateResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateResponse' from JSON`,
  );
}
