/**
 * Fixture addresses for integration tests. Minimal set chosen to exercise
 * all the search semantics edge cases we care about:
 *
 * - Multiple HEATH ___ variants (ROAD, STREET, CRESCENT) for ranking tests
 * - HEATH CRESCENT in two states (NSW, VIC) for multi-state suburb tests
 * - BONDI BEACH for suburb fuzzy match tests
 * - RICHMOND in three states for multi-state aggregation tests
 * - SYDNEY / HAYMARKET for postcode-lookup tests
 * - BIGTOWN × 4 vs BIGTOWM × 1 for fuzzy-tiebreak-by-count tests
 *
 * `numberFirst` is populated on every doc so the street-number gate in
 * scoreToConfidence() fires in tests. In real G-NAF data it's extracted
 * from the unstructured address string during ingestion.
 */
export const fixtureAddresses = [
  {
    id: "F_GANSW704893526",
    addressLabel: "16 HEATH CRESCENT",
    addressLabelSearch: "16 HEATH CRESCENT GRIFFITH NSW 2680",
    localityName: "GRIFFITH",
    state: "NSW",
    postcode: "2680",
    confidence: 2,
    location: { lat: -34.293, lon: 146.039 },
    numberFirst: "16",
  },
  {
    id: "F_GAVIC420559144",
    addressLabel: "16 HEATH CRESCENT",
    addressLabelSearch: "16 HEATH CRESCENT HAMPTON EAST VIC 3188",
    localityName: "HAMPTON EAST",
    state: "VIC",
    postcode: "3188",
    confidence: 2,
    location: { lat: -37.9376, lon: 145.0295 },
    numberFirst: "16",
  },
  {
    id: "F_GANSW720158070",
    addressLabel: "16 HEATH ROAD",
    addressLabelSearch: "16 HEATH ROAD LEPPINGTON NSW 2179",
    localityName: "LEPPINGTON",
    state: "NSW",
    postcode: "2179",
    confidence: 2,
    location: { lat: -33.979, lon: 150.811 },
    numberFirst: "16",
  },
  {
    id: "F_GASA_415543154",
    addressLabel: "16 HEATH STREET",
    addressLabelSearch: "16 HEATH STREET BIRKENHEAD SA 5015",
    localityName: "BIRKENHEAD",
    state: "SA",
    postcode: "5015",
    confidence: 2,
    location: { lat: -34.838, lon: 138.498 },
    numberFirst: "16",
  },
  {
    id: "F_GANSW706085480",
    addressLabel: "16 HEATH AVENUE",
    addressLabelSearch: "16 HEATH AVENUE TUNCURRY NSW 2428",
    localityName: "TUNCURRY",
    state: "NSW",
    postcode: "2428",
    confidence: 2,
    location: { lat: -32.175, lon: 152.507 },
    numberFirst: "16",
  },
  {
    id: "F_BONDI_BEACH_1",
    addressLabel: "1 BONDI ROAD",
    addressLabelSearch: "1 BONDI ROAD BONDI BEACH NSW 2026",
    localityName: "BONDI BEACH",
    state: "NSW",
    postcode: "2026",
    confidence: 2,
    location: { lat: -33.892, lon: 151.277 },
    numberFirst: "1",
  },
  {
    id: "F_BONDI_BEACH_2",
    addressLabel: "2 CAMPBELL PARADE",
    addressLabelSearch: "2 CAMPBELL PARADE BONDI BEACH NSW 2026",
    localityName: "BONDI BEACH",
    state: "NSW",
    postcode: "2026",
    confidence: 2,
    location: { lat: -33.891, lon: 151.278 },
    numberFirst: "2",
  },
  {
    id: "F_RICHMOND_VIC",
    addressLabel: "1 BRIDGE ROAD",
    addressLabelSearch: "1 BRIDGE ROAD RICHMOND VIC 3121",
    localityName: "RICHMOND",
    state: "VIC",
    postcode: "3121",
    confidence: 2,
    location: { lat: -37.818, lon: 144.998 },
    numberFirst: "1",
  },
  {
    id: "F_RICHMOND_NSW",
    addressLabel: "1 WINDSOR STREET",
    addressLabelSearch: "1 WINDSOR STREET RICHMOND NSW 2753",
    localityName: "RICHMOND",
    state: "NSW",
    postcode: "2753",
    confidence: 2,
    location: { lat: -33.598, lon: 150.749 },
    numberFirst: "1",
  },
  {
    id: "F_RICHMOND_TAS",
    addressLabel: "1 BRIDGE STREET",
    addressLabelSearch: "1 BRIDGE STREET RICHMOND TAS 7025",
    localityName: "RICHMOND",
    state: "TAS",
    postcode: "7025",
    confidence: 2,
    location: { lat: -42.735, lon: 147.438 },
    numberFirst: "1",
  },
  {
    id: "F_SYDNEY_1",
    addressLabel: "1 MARTIN PLACE",
    addressLabelSearch: "1 MARTIN PLACE SYDNEY NSW 2000",
    localityName: "SYDNEY",
    state: "NSW",
    postcode: "2000",
    confidence: 2,
    location: { lat: -33.867, lon: 151.209 },
    numberFirst: "1",
  },
  {
    id: "F_HAYMARKET_1",
    addressLabel: "1 GEORGE STREET",
    addressLabelSearch: "1 GEORGE STREET HAYMARKET NSW 2000",
    localityName: "HAYMARKET",
    state: "NSW",
    postcode: "2000",
    confidence: 2,
    location: { lat: -33.878, lon: 151.205 },
    numberFirst: "1",
  },
  // ---- Fuzzy tie-break fixtures ----
  // BIGTOWN = 4 addresses (populous), BIGTOWM = 1 address (rare, 1 edit away).
  // Query "BIGTOWS" fuzzy-matches both; count-ordered agg must prefer BIGTOWN.
  // Exact query "BIGTOWM" must still return BIGTOWM (rare exact must win).
  {
    id: "F_BIGTOWN_1",
    addressLabel: "1 MAIN STREET",
    addressLabelSearch: "1 MAIN STREET BIGTOWN WA 6000",
    localityName: "BIGTOWN",
    state: "WA",
    postcode: "6000",
    confidence: 2,
    location: { lat: -31.0, lon: 115.0 },
    numberFirst: "1",
  },
  {
    id: "F_BIGTOWN_2",
    addressLabel: "2 MAIN STREET",
    addressLabelSearch: "2 MAIN STREET BIGTOWN WA 6000",
    localityName: "BIGTOWN",
    state: "WA",
    postcode: "6000",
    confidence: 2,
    location: { lat: -31.0, lon: 115.0 },
    numberFirst: "2",
  },
  {
    id: "F_BIGTOWN_3",
    addressLabel: "3 MAIN STREET",
    addressLabelSearch: "3 MAIN STREET BIGTOWN WA 6000",
    localityName: "BIGTOWN",
    state: "WA",
    postcode: "6000",
    confidence: 2,
    location: { lat: -31.0, lon: 115.0 },
    numberFirst: "3",
  },
  {
    id: "F_BIGTOWN_4",
    addressLabel: "4 MAIN STREET",
    addressLabelSearch: "4 MAIN STREET BIGTOWN WA 6000",
    localityName: "BIGTOWN",
    state: "WA",
    postcode: "6000",
    confidence: 2,
    location: { lat: -31.0, lon: 115.0 },
    numberFirst: "4",
  },
  {
    id: "F_BIGTOWM_1",
    addressLabel: "1 MAIN STREET",
    addressLabelSearch: "1 MAIN STREET BIGTOWM WA 6001",
    localityName: "BIGTOWM",
    state: "WA",
    postcode: "6001",
    confidence: 2,
    location: { lat: -31.0, lon: 115.0 },
    numberFirst: "1",
  },
  // ---- Closer-rare vs farther-populous fixtures ----
  // Query "AVOCAL": AVOCA (5 chars, 1 edit: delete L) vs AVOCADO (7 chars,
  // 2 edits: L→D + insert O). Correct behavior: AVOCA wins on lexical
  // closeness even though AVOCADO has more addresses. Guards against the
  // "population overrides closeness" regression.
  {
    id: "F_AVOCA_1",
    addressLabel: "1 BEACH ROAD",
    addressLabelSearch: "1 BEACH ROAD AVOCA NSW 2251",
    localityName: "AVOCA",
    state: "NSW",
    postcode: "2251",
    confidence: 2,
    location: { lat: -33.47, lon: 151.44 },
    numberFirst: "1",
  },
  {
    id: "F_AVOCADO_1",
    addressLabel: "1 ORCHARD ROAD",
    addressLabelSearch: "1 ORCHARD ROAD AVOCADO NSW 2250",
    localityName: "AVOCADO",
    state: "NSW",
    postcode: "2250",
    confidence: 2,
    location: { lat: -33.43, lon: 151.34 },
    numberFirst: "1",
  },
  {
    id: "F_AVOCADO_2",
    addressLabel: "2 ORCHARD ROAD",
    addressLabelSearch: "2 ORCHARD ROAD AVOCADO NSW 2250",
    localityName: "AVOCADO",
    state: "NSW",
    postcode: "2250",
    confidence: 2,
    location: { lat: -33.43, lon: 151.34 },
    numberFirst: "2",
  },
  {
    id: "F_AVOCADO_3",
    addressLabel: "3 ORCHARD ROAD",
    addressLabelSearch: "3 ORCHARD ROAD AVOCADO NSW 2250",
    localityName: "AVOCADO",
    state: "NSW",
    postcode: "2250",
    confidence: 2,
    location: { lat: -33.43, lon: 151.34 },
    numberFirst: "3",
  },
  {
    id: "F_AVOCADO_4",
    addressLabel: "4 ORCHARD ROAD",
    addressLabelSearch: "4 ORCHARD ROAD AVOCADO NSW 2250",
    localityName: "AVOCADO",
    state: "NSW",
    postcode: "2250",
    confidence: 2,
    location: { lat: -33.43, lon: 151.34 },
    numberFirst: "4",
  },
  {
    id: "F_AVOCADO_5",
    addressLabel: "5 ORCHARD ROAD",
    addressLabelSearch: "5 ORCHARD ROAD AVOCADO NSW 2250",
    localityName: "AVOCADO",
    state: "NSW",
    postcode: "2250",
    confidence: 2,
    location: { lat: -33.43, lon: 151.34 },
    numberFirst: "5",
  },
];

/**
 * Minimal OpenSearch mappings matching prod for the fields our queries use.
 * The real prod mapping includes many more fields (G-NAF enrichment data),
 * but these are the ones required for queries in queries.ts.
 */
export const fixtureMappings = {
  properties: {
    addressLabelSearch: { type: "search_as_you_type" },
    addressLabel: { type: "keyword" },
    localityName: { type: "keyword" },
    state: { type: "keyword" },
    postcode: { type: "keyword" },
    confidence: { type: "integer" },
    location: { type: "geo_point" },
    numberFirst: { type: "keyword" },
  },
} as const;
