/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getV1AddressAutocomplete } from "../funcs/get-v1-address-autocomplete.js";
import { getV1AddressEnrich } from "../funcs/get-v1-address-enrich.js";
import { getV1AddressLookupPostcode } from "../funcs/get-v1-address-lookup-postcode.js";
import { getV1AddressLookupSuburb } from "../funcs/get-v1-address-lookup-suburb.js";
import { getV1AddressReverse } from "../funcs/get-v1-address-reverse.js";
import { getV1AddressValidate } from "../funcs/get-v1-address-validate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Prontiq extends ClientSDK {
  /**
   * Autocomplete addresses
   */
  async getV1AddressAutocomplete(
    q: string,
    state?: string | undefined,
    limit?: number | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1AddressAutocompleteResponseBody> {
    return unwrapAsync(getV1AddressAutocomplete(
      this,
      q,
      state,
      limit,
      options,
    ));
  }

  /**
   * Validate an address
   */
  async getV1AddressValidate(
    q: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1AddressValidateResponseBody> {
    return unwrapAsync(getV1AddressValidate(
      this,
      q,
      options,
    ));
  }

  /**
   * Enrich an address by ID
   */
  async getV1AddressEnrich(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1AddressEnrichResponseBody> {
    return unwrapAsync(getV1AddressEnrich(
      this,
      id,
      options,
    ));
  }

  /**
   * Reverse geocode nearby addresses
   */
  async getV1AddressReverse(
    lat: number,
    lon: number,
    radius?: number | undefined,
    limit?: number | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1AddressReverseResponseBody> {
    return unwrapAsync(getV1AddressReverse(
      this,
      lat,
      lon,
      radius,
      limit,
      options,
    ));
  }

  /**
   * Look up localities by postcode
   */
  async getV1AddressLookupPostcode(
    postcode: string,
    limit?: number | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1AddressLookupPostcodeResponseBody> {
    return unwrapAsync(getV1AddressLookupPostcode(
      this,
      postcode,
      limit,
      options,
    ));
  }

  /**
   * Look up postcodes by suburb
   */
  async getV1AddressLookupSuburb(
    suburb: string,
    state?: string | undefined,
    limit?: number | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1AddressLookupSuburbResponseBody> {
    return unwrapAsync(getV1AddressLookupSuburb(
      this,
      suburb,
      state,
      limit,
      options,
    ));
  }
}
