/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { ProntiqError } from "./prontiq-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetV1AddressAutocompleteResponse500Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Internal server error
 */
export type GetV1AddressAutocompleteResponse500ResponseBodyData = {
  error: GetV1AddressAutocompleteResponse500Error;
};

/**
 * Internal server error
 */
export class GetV1AddressAutocompleteResponse500ResponseBody
  extends ProntiqError
{
  error: GetV1AddressAutocompleteResponse500Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressAutocompleteResponse500ResponseBodyData;

  constructor(
    err: GetV1AddressAutocompleteResponse500ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressAutocompleteResponse500ResponseBody";
  }
}

export type GetV1AddressAutocompleteResponse429Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Rate limit or quota exceeded
 */
export type GetV1AddressAutocompleteResponse429ResponseBodyData = {
  error: GetV1AddressAutocompleteResponse429Error;
};

/**
 * Rate limit or quota exceeded
 */
export class GetV1AddressAutocompleteResponse429ResponseBody
  extends ProntiqError
{
  error: GetV1AddressAutocompleteResponse429Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressAutocompleteResponse429ResponseBodyData;

  constructor(
    err: GetV1AddressAutocompleteResponse429ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressAutocompleteResponse429ResponseBody";
  }
}

export type GetV1AddressAutocompleteResponseError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Product not included in plan
 */
export type GetV1AddressAutocompleteResponse403ResponseBodyData = {
  error: GetV1AddressAutocompleteResponseError;
};

/**
 * Product not included in plan
 */
export class GetV1AddressAutocompleteResponse403ResponseBody
  extends ProntiqError
{
  error: GetV1AddressAutocompleteResponseError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressAutocompleteResponse403ResponseBodyData;

  constructor(
    err: GetV1AddressAutocompleteResponse403ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressAutocompleteResponse403ResponseBody";
  }
}

export type GetV1AddressAutocompleteError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Missing or invalid API key
 */
export type GetV1AddressAutocompleteResponseResponseBodyData = {
  error: GetV1AddressAutocompleteError;
};

/**
 * Missing or invalid API key
 */
export class GetV1AddressAutocompleteResponseResponseBody extends ProntiqError {
  error: GetV1AddressAutocompleteError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressAutocompleteResponseResponseBodyData;

  constructor(
    err: GetV1AddressAutocompleteResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressAutocompleteResponseResponseBody";
  }
}

export type ErrorT = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Invalid query parameters
 */
export type GetV1AddressAutocompleteResponseBodyData = {
  error: ErrorT;
};

/**
 * Invalid query parameters
 */
export class GetV1AddressAutocompleteResponseBody extends ProntiqError {
  error: ErrorT;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressAutocompleteResponseBodyData;

  constructor(
    err: GetV1AddressAutocompleteResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressAutocompleteResponseBody";
  }
}

/** @internal */
export const GetV1AddressAutocompleteResponse500Error$inboundSchema:
  z.ZodMiniType<GetV1AddressAutocompleteResponse500Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressAutocompleteResponse500ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressAutocompleteResponse500Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressAutocompleteResponse500Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressAutocompleteResponse500Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressAutocompleteResponse500ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressAutocompleteResponse500ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressAutocompleteResponse500Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressAutocompleteResponse500ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressAutocompleteResponse429Error$inboundSchema:
  z.ZodMiniType<GetV1AddressAutocompleteResponse429Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressAutocompleteResponse429ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressAutocompleteResponse429Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressAutocompleteResponse429Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressAutocompleteResponse429Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressAutocompleteResponse429ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressAutocompleteResponse429ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressAutocompleteResponse429Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressAutocompleteResponse429ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressAutocompleteResponseError$inboundSchema: z.ZodMiniType<
  GetV1AddressAutocompleteResponseError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressAutocompleteResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressAutocompleteResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressAutocompleteResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressAutocompleteResponseError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressAutocompleteResponse403ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressAutocompleteResponse403ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressAutocompleteResponseError$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressAutocompleteResponse403ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressAutocompleteError$inboundSchema: z.ZodMiniType<
  GetV1AddressAutocompleteError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressAutocompleteErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressAutocompleteError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressAutocompleteError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressAutocompleteError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressAutocompleteResponseResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressAutocompleteResponseResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressAutocompleteError$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressAutocompleteResponseResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const GetV1AddressAutocompleteResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressAutocompleteResponseBody,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => ErrorT$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetV1AddressAutocompleteResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
