/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { ProntiqError } from "./prontiq-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetV1AddressReverseResponse500Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Internal server error
 */
export type GetV1AddressReverseResponse500ResponseBodyData = {
  error: GetV1AddressReverseResponse500Error;
};

/**
 * Internal server error
 */
export class GetV1AddressReverseResponse500ResponseBody extends ProntiqError {
  error: GetV1AddressReverseResponse500Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressReverseResponse500ResponseBodyData;

  constructor(
    err: GetV1AddressReverseResponse500ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressReverseResponse500ResponseBody";
  }
}

export type GetV1AddressReverseResponse429Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Rate limit or quota exceeded
 */
export type GetV1AddressReverseResponse429ResponseBodyData = {
  error: GetV1AddressReverseResponse429Error;
};

/**
 * Rate limit or quota exceeded
 */
export class GetV1AddressReverseResponse429ResponseBody extends ProntiqError {
  error: GetV1AddressReverseResponse429Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressReverseResponse429ResponseBodyData;

  constructor(
    err: GetV1AddressReverseResponse429ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressReverseResponse429ResponseBody";
  }
}

export type GetV1AddressReverseResponse403Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Product not included in plan
 */
export type GetV1AddressReverseResponse403ResponseBodyData = {
  error: GetV1AddressReverseResponse403Error;
};

/**
 * Product not included in plan
 */
export class GetV1AddressReverseResponse403ResponseBody extends ProntiqError {
  error: GetV1AddressReverseResponse403Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressReverseResponse403ResponseBodyData;

  constructor(
    err: GetV1AddressReverseResponse403ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressReverseResponse403ResponseBody";
  }
}

export type GetV1AddressReverseResponseError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Missing or invalid API key
 */
export type GetV1AddressReverseResponseResponseBodyData = {
  error: GetV1AddressReverseResponseError;
};

/**
 * Missing or invalid API key
 */
export class GetV1AddressReverseResponseResponseBody extends ProntiqError {
  error: GetV1AddressReverseResponseError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressReverseResponseResponseBodyData;

  constructor(
    err: GetV1AddressReverseResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressReverseResponseResponseBody";
  }
}

export type GetV1AddressReverseError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Invalid query parameters
 */
export type GetV1AddressReverseResponseBodyData = {
  error: GetV1AddressReverseError;
};

/**
 * Invalid query parameters
 */
export class GetV1AddressReverseResponseBody extends ProntiqError {
  error: GetV1AddressReverseError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressReverseResponseBodyData;

  constructor(
    err: GetV1AddressReverseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressReverseResponseBody";
  }
}

/** @internal */
export const GetV1AddressReverseResponse500Error$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseResponse500Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressReverseResponse500ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseResponse500Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressReverseResponse500Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseResponse500Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseResponse500ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressReverseResponse500ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressReverseResponse500Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressReverseResponse500ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressReverseResponse429Error$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseResponse429Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressReverseResponse429ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseResponse429Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressReverseResponse429Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseResponse429Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseResponse429ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressReverseResponse429ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressReverseResponse429Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressReverseResponse429ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressReverseResponse403Error$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseResponse403Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressReverseResponse403ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseResponse403Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressReverseResponse403Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseResponse403Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseResponse403ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressReverseResponse403ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressReverseResponse403Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressReverseResponse403ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressReverseResponseError$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseResponseError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressReverseResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseResponseError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseResponseResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressReverseResponseResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressReverseResponseError$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressReverseResponseResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressReverseError$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressReverseErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressReverseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressReverseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressReverseError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressReverseResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressReverseResponseBody,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => GetV1AddressReverseError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetV1AddressReverseResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
