/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { ProntiqError } from "./prontiq-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetV1AddressEnrichResponse500Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Internal server error
 */
export type GetV1AddressEnrichResponse500ResponseBodyData = {
  error: GetV1AddressEnrichResponse500Error;
};

/**
 * Internal server error
 */
export class GetV1AddressEnrichResponse500ResponseBody extends ProntiqError {
  error: GetV1AddressEnrichResponse500Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressEnrichResponse500ResponseBodyData;

  constructor(
    err: GetV1AddressEnrichResponse500ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressEnrichResponse500ResponseBody";
  }
}

export type GetV1AddressEnrichResponse429Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Rate limit or quota exceeded
 */
export type GetV1AddressEnrichResponse429ResponseBodyData = {
  error: GetV1AddressEnrichResponse429Error;
};

/**
 * Rate limit or quota exceeded
 */
export class GetV1AddressEnrichResponse429ResponseBody extends ProntiqError {
  error: GetV1AddressEnrichResponse429Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressEnrichResponse429ResponseBodyData;

  constructor(
    err: GetV1AddressEnrichResponse429ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressEnrichResponse429ResponseBody";
  }
}

export type GetV1AddressEnrichResponse404Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Address not found
 */
export type GetV1AddressEnrichResponse404ResponseBodyData = {
  error: GetV1AddressEnrichResponse404Error;
};

/**
 * Address not found
 */
export class GetV1AddressEnrichResponse404ResponseBody extends ProntiqError {
  error: GetV1AddressEnrichResponse404Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressEnrichResponse404ResponseBodyData;

  constructor(
    err: GetV1AddressEnrichResponse404ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressEnrichResponse404ResponseBody";
  }
}

export type GetV1AddressEnrichResponse403Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Product not included in plan
 */
export type GetV1AddressEnrichResponse403ResponseBodyData = {
  error: GetV1AddressEnrichResponse403Error;
};

/**
 * Product not included in plan
 */
export class GetV1AddressEnrichResponse403ResponseBody extends ProntiqError {
  error: GetV1AddressEnrichResponse403Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressEnrichResponse403ResponseBodyData;

  constructor(
    err: GetV1AddressEnrichResponse403ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressEnrichResponse403ResponseBody";
  }
}

export type GetV1AddressEnrichResponseError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Missing or invalid API key
 */
export type GetV1AddressEnrichResponseResponseBodyData = {
  error: GetV1AddressEnrichResponseError;
};

/**
 * Missing or invalid API key
 */
export class GetV1AddressEnrichResponseResponseBody extends ProntiqError {
  error: GetV1AddressEnrichResponseError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressEnrichResponseResponseBodyData;

  constructor(
    err: GetV1AddressEnrichResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressEnrichResponseResponseBody";
  }
}

export type GetV1AddressEnrichError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Invalid query parameters
 */
export type GetV1AddressEnrichResponseBodyData = {
  error: GetV1AddressEnrichError;
};

/**
 * Invalid query parameters
 */
export class GetV1AddressEnrichResponseBody extends ProntiqError {
  error: GetV1AddressEnrichError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressEnrichResponseBodyData;

  constructor(
    err: GetV1AddressEnrichResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressEnrichResponseBody";
  }
}

/** @internal */
export const GetV1AddressEnrichResponse500Error$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponse500Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressEnrichResponse500ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichResponse500Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressEnrichResponse500Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichResponse500Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponse500ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressEnrichResponse500ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressEnrichResponse500Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressEnrichResponse500ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressEnrichResponse429Error$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponse429Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressEnrichResponse429ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichResponse429Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressEnrichResponse429Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichResponse429Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponse429ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressEnrichResponse429ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressEnrichResponse429Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressEnrichResponse429ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressEnrichResponse404Error$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponse404Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressEnrichResponse404ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichResponse404Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressEnrichResponse404Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichResponse404Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponse404ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressEnrichResponse404ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressEnrichResponse404Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressEnrichResponse404ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressEnrichResponse403Error$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponse403Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressEnrichResponse403ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichResponse403Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressEnrichResponse403Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichResponse403Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponse403ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressEnrichResponse403ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressEnrichResponse403Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressEnrichResponse403ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressEnrichResponseError$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponseError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressEnrichResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressEnrichResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichResponseError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponseResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressEnrichResponseResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressEnrichResponseError$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressEnrichResponseResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressEnrichError$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressEnrichErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressEnrichError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressEnrichError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressEnrichError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressEnrichResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressEnrichResponseBody,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => GetV1AddressEnrichError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetV1AddressEnrichResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
