/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { ProntiqError } from "./prontiq-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetV1AddressLookupSuburbResponse500Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Internal server error
 */
export type GetV1AddressLookupSuburbResponse500ResponseBodyData = {
  error: GetV1AddressLookupSuburbResponse500Error;
};

/**
 * Internal server error
 */
export class GetV1AddressLookupSuburbResponse500ResponseBody
  extends ProntiqError
{
  error: GetV1AddressLookupSuburbResponse500Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupSuburbResponse500ResponseBodyData;

  constructor(
    err: GetV1AddressLookupSuburbResponse500ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupSuburbResponse500ResponseBody";
  }
}

export type GetV1AddressLookupSuburbResponse429Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Rate limit or quota exceeded
 */
export type GetV1AddressLookupSuburbResponse429ResponseBodyData = {
  error: GetV1AddressLookupSuburbResponse429Error;
};

/**
 * Rate limit or quota exceeded
 */
export class GetV1AddressLookupSuburbResponse429ResponseBody
  extends ProntiqError
{
  error: GetV1AddressLookupSuburbResponse429Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupSuburbResponse429ResponseBodyData;

  constructor(
    err: GetV1AddressLookupSuburbResponse429ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupSuburbResponse429ResponseBody";
  }
}

export type GetV1AddressLookupSuburbResponse403Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Product not included in plan
 */
export type GetV1AddressLookupSuburbResponse403ResponseBodyData = {
  error: GetV1AddressLookupSuburbResponse403Error;
};

/**
 * Product not included in plan
 */
export class GetV1AddressLookupSuburbResponse403ResponseBody
  extends ProntiqError
{
  error: GetV1AddressLookupSuburbResponse403Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupSuburbResponse403ResponseBodyData;

  constructor(
    err: GetV1AddressLookupSuburbResponse403ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupSuburbResponse403ResponseBody";
  }
}

export type GetV1AddressLookupSuburbResponseError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Missing or invalid API key
 */
export type GetV1AddressLookupSuburbResponseResponseBodyData = {
  error: GetV1AddressLookupSuburbResponseError;
};

/**
 * Missing or invalid API key
 */
export class GetV1AddressLookupSuburbResponseResponseBody extends ProntiqError {
  error: GetV1AddressLookupSuburbResponseError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupSuburbResponseResponseBodyData;

  constructor(
    err: GetV1AddressLookupSuburbResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupSuburbResponseResponseBody";
  }
}

export type GetV1AddressLookupSuburbError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Invalid query parameters
 */
export type GetV1AddressLookupSuburbResponseBodyData = {
  error: GetV1AddressLookupSuburbError;
};

/**
 * Invalid query parameters
 */
export class GetV1AddressLookupSuburbResponseBody extends ProntiqError {
  error: GetV1AddressLookupSuburbError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupSuburbResponseBodyData;

  constructor(
    err: GetV1AddressLookupSuburbResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupSuburbResponseBody";
  }
}

/** @internal */
export const GetV1AddressLookupSuburbResponse500Error$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupSuburbResponse500Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressLookupSuburbResponse500ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressLookupSuburbResponse500Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupSuburbResponse500Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressLookupSuburbResponse500Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupSuburbResponse500ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupSuburbResponse500ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressLookupSuburbResponse500Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressLookupSuburbResponse500ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressLookupSuburbResponse429Error$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupSuburbResponse429Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressLookupSuburbResponse429ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressLookupSuburbResponse429Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupSuburbResponse429Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressLookupSuburbResponse429Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupSuburbResponse429ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupSuburbResponse429ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressLookupSuburbResponse429Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressLookupSuburbResponse429ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressLookupSuburbResponse403Error$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupSuburbResponse403Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressLookupSuburbResponse403ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressLookupSuburbResponse403Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupSuburbResponse403Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressLookupSuburbResponse403Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupSuburbResponse403ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupSuburbResponse403ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressLookupSuburbResponse403Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressLookupSuburbResponse403ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressLookupSuburbResponseError$inboundSchema: z.ZodMiniType<
  GetV1AddressLookupSuburbResponseError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressLookupSuburbResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressLookupSuburbResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupSuburbResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressLookupSuburbResponseError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupSuburbResponseResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupSuburbResponseResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressLookupSuburbResponseError$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressLookupSuburbResponseResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressLookupSuburbError$inboundSchema: z.ZodMiniType<
  GetV1AddressLookupSuburbError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressLookupSuburbErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressLookupSuburbError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressLookupSuburbError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressLookupSuburbError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupSuburbResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressLookupSuburbResponseBody,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => GetV1AddressLookupSuburbError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetV1AddressLookupSuburbResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
