/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { ProntiqError } from "./prontiq-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetV1AddressLookupPostcodeResponse500Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Internal server error
 */
export type GetV1AddressLookupPostcodeResponse500ResponseBodyData = {
  error: GetV1AddressLookupPostcodeResponse500Error;
};

/**
 * Internal server error
 */
export class GetV1AddressLookupPostcodeResponse500ResponseBody
  extends ProntiqError
{
  error: GetV1AddressLookupPostcodeResponse500Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupPostcodeResponse500ResponseBodyData;

  constructor(
    err: GetV1AddressLookupPostcodeResponse500ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupPostcodeResponse500ResponseBody";
  }
}

export type GetV1AddressLookupPostcodeResponse429Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Rate limit or quota exceeded
 */
export type GetV1AddressLookupPostcodeResponse429ResponseBodyData = {
  error: GetV1AddressLookupPostcodeResponse429Error;
};

/**
 * Rate limit or quota exceeded
 */
export class GetV1AddressLookupPostcodeResponse429ResponseBody
  extends ProntiqError
{
  error: GetV1AddressLookupPostcodeResponse429Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupPostcodeResponse429ResponseBodyData;

  constructor(
    err: GetV1AddressLookupPostcodeResponse429ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupPostcodeResponse429ResponseBody";
  }
}

export type GetV1AddressLookupPostcodeResponse403Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Product not included in plan
 */
export type GetV1AddressLookupPostcodeResponse403ResponseBodyData = {
  error: GetV1AddressLookupPostcodeResponse403Error;
};

/**
 * Product not included in plan
 */
export class GetV1AddressLookupPostcodeResponse403ResponseBody
  extends ProntiqError
{
  error: GetV1AddressLookupPostcodeResponse403Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupPostcodeResponse403ResponseBodyData;

  constructor(
    err: GetV1AddressLookupPostcodeResponse403ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupPostcodeResponse403ResponseBody";
  }
}

export type GetV1AddressLookupPostcodeResponseError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Missing or invalid API key
 */
export type GetV1AddressLookupPostcodeResponseResponseBodyData = {
  error: GetV1AddressLookupPostcodeResponseError;
};

/**
 * Missing or invalid API key
 */
export class GetV1AddressLookupPostcodeResponseResponseBody
  extends ProntiqError
{
  error: GetV1AddressLookupPostcodeResponseError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupPostcodeResponseResponseBodyData;

  constructor(
    err: GetV1AddressLookupPostcodeResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupPostcodeResponseResponseBody";
  }
}

export type GetV1AddressLookupPostcodeError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Invalid query parameters
 */
export type GetV1AddressLookupPostcodeResponseBodyData = {
  error: GetV1AddressLookupPostcodeError;
};

/**
 * Invalid query parameters
 */
export class GetV1AddressLookupPostcodeResponseBody extends ProntiqError {
  error: GetV1AddressLookupPostcodeError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressLookupPostcodeResponseBodyData;

  constructor(
    err: GetV1AddressLookupPostcodeResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressLookupPostcodeResponseBody";
  }
}

/** @internal */
export const GetV1AddressLookupPostcodeResponse500Error$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponse500Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressLookupPostcodeResponse500ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressLookupPostcodeResponse500Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupPostcodeResponse500Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressLookupPostcodeResponse500Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupPostcodeResponse500ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponse500ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressLookupPostcodeResponse500Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressLookupPostcodeResponse500ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressLookupPostcodeResponse429Error$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponse429Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressLookupPostcodeResponse429ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressLookupPostcodeResponse429Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupPostcodeResponse429Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressLookupPostcodeResponse429Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupPostcodeResponse429ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponse429ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressLookupPostcodeResponse429Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressLookupPostcodeResponse429ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressLookupPostcodeResponse403Error$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponse403Error, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressLookupPostcodeResponse403ErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressLookupPostcodeResponse403Error,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupPostcodeResponse403Error$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressLookupPostcodeResponse403Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupPostcodeResponse403ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponse403ResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressLookupPostcodeResponse403Error$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressLookupPostcodeResponse403ResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressLookupPostcodeResponseError$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponseError, unknown> = z.pipe(
    z.object({
      code: types.string(),
      message: types.string(),
      status: types.number(),
      request_id: types.string(),
      details: types.optional(z.record(z.string(), z.any())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "request_id": "requestId",
      });
    }),
  );

export function getV1AddressLookupPostcodeResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1AddressLookupPostcodeResponseError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressLookupPostcodeResponseError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1AddressLookupPostcodeResponseError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupPostcodeResponseResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponseResponseBody, unknown> = z
    .pipe(
      z.object({
        error: z.lazy(() =>
          GetV1AddressLookupPostcodeResponseError$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetV1AddressLookupPostcodeResponseResponseBody(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetV1AddressLookupPostcodeError$inboundSchema: z.ZodMiniType<
  GetV1AddressLookupPostcodeError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressLookupPostcodeErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressLookupPostcodeError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressLookupPostcodeError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressLookupPostcodeError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressLookupPostcodeResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressLookupPostcodeResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressLookupPostcodeError$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressLookupPostcodeResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
