/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { ProntiqError } from "./prontiq-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type GetV1AddressValidateResponse500Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Internal server error
 */
export type GetV1AddressValidateResponse500ResponseBodyData = {
  error: GetV1AddressValidateResponse500Error;
};

/**
 * Internal server error
 */
export class GetV1AddressValidateResponse500ResponseBody extends ProntiqError {
  error: GetV1AddressValidateResponse500Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressValidateResponse500ResponseBodyData;

  constructor(
    err: GetV1AddressValidateResponse500ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressValidateResponse500ResponseBody";
  }
}

export type GetV1AddressValidateResponse429Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Rate limit or quota exceeded
 */
export type GetV1AddressValidateResponse429ResponseBodyData = {
  error: GetV1AddressValidateResponse429Error;
};

/**
 * Rate limit or quota exceeded
 */
export class GetV1AddressValidateResponse429ResponseBody extends ProntiqError {
  error: GetV1AddressValidateResponse429Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressValidateResponse429ResponseBodyData;

  constructor(
    err: GetV1AddressValidateResponse429ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressValidateResponse429ResponseBody";
  }
}

export type GetV1AddressValidateResponse403Error = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Product not included in plan
 */
export type GetV1AddressValidateResponse403ResponseBodyData = {
  error: GetV1AddressValidateResponse403Error;
};

/**
 * Product not included in plan
 */
export class GetV1AddressValidateResponse403ResponseBody extends ProntiqError {
  error: GetV1AddressValidateResponse403Error;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressValidateResponse403ResponseBodyData;

  constructor(
    err: GetV1AddressValidateResponse403ResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressValidateResponse403ResponseBody";
  }
}

export type GetV1AddressValidateResponseError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Missing or invalid API key
 */
export type GetV1AddressValidateResponseResponseBodyData = {
  error: GetV1AddressValidateResponseError;
};

/**
 * Missing or invalid API key
 */
export class GetV1AddressValidateResponseResponseBody extends ProntiqError {
  error: GetV1AddressValidateResponseError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressValidateResponseResponseBodyData;

  constructor(
    err: GetV1AddressValidateResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressValidateResponseResponseBody";
  }
}

export type GetV1AddressValidateError = {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: { [k: string]: any } | undefined;
};

/**
 * Invalid query parameters
 */
export type GetV1AddressValidateResponseBodyData = {
  error: GetV1AddressValidateError;
};

/**
 * Invalid query parameters
 */
export class GetV1AddressValidateResponseBody extends ProntiqError {
  error: GetV1AddressValidateError;

  /** The original data that was passed to this error instance. */
  data$: GetV1AddressValidateResponseBodyData;

  constructor(
    err: GetV1AddressValidateResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetV1AddressValidateResponseBody";
  }
}

/** @internal */
export const GetV1AddressValidateResponse500Error$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateResponse500Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressValidateResponse500ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateResponse500Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressValidateResponse500Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateResponse500Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateResponse500ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressValidateResponse500ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressValidateResponse500Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressValidateResponse500ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressValidateResponse429Error$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateResponse429Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressValidateResponse429ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateResponse429Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressValidateResponse429Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateResponse429Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateResponse429ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressValidateResponse429ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressValidateResponse429Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressValidateResponse429ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressValidateResponse403Error$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateResponse403Error,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressValidateResponse403ErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateResponse403Error, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1AddressValidateResponse403Error$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateResponse403Error' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateResponse403ResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressValidateResponse403ResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressValidateResponse403Error$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressValidateResponse403ResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressValidateResponseError$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateResponseError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressValidateResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateResponseError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateResponseResponseBody$inboundSchema:
  z.ZodMiniType<GetV1AddressValidateResponseResponseBody, unknown> = z.pipe(
    z.object({
      error: z.lazy(() => GetV1AddressValidateResponseError$inboundSchema),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetV1AddressValidateResponseResponseBody(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetV1AddressValidateError$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateError,
  unknown
> = z.pipe(
  z.object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    request_id: types.string(),
    details: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
    });
  }),
);

export function getV1AddressValidateErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1AddressValidateError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1AddressValidateError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1AddressValidateError' from JSON`,
  );
}

/** @internal */
export const GetV1AddressValidateResponseBody$inboundSchema: z.ZodMiniType<
  GetV1AddressValidateResponseBody,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => GetV1AddressValidateError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetV1AddressValidateResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
