name: Generate SDKs

on:
  push:
    branches: [main]
    paths:
      - "packages/docs/openapi.json"
      - ".speakeasy/**"
  workflow_dispatch:
    inputs:
      force:
        description: Force SDK generation, even if no changes are detected.
        type: boolean
        default: false

permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      speakeasy_version: "1.761.3"
      force: ${{ github.event.inputs.force || false }}
      mode: pr
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      npm_token: ${{ secrets.NPM_TOKEN }}
