/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @prontiq/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx getV1AddressAutocomplete.example.ts
 */

import { Prontiq } from "@prontiq/sdk";

const prontiq = new Prontiq({
  serverURL: "https://api.example.com",
  apiKeyAuth: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await prontiq.getV1AddressAutocomplete("<value>");

  console.log(result);
}

main().catch(console.error);
